// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"

	"SEproject/provider"
)

func Init() {
	provider.Init()
}

func main() {
	Init()
	h := server.Default()

	register(h)
	h.Spin()
}
