// Code generated by goctl. DO NOT EDIT.

package mapper

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	signInFieldNames          = builder.RawFieldNames(&SignIn{})
	signInRows                = strings.Join(signInFieldNames, ",")
	signInRowsExpectAutoSet   = strings.Join(stringx.Remove(signInFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	signInRowsWithPlaceHolder = strings.Join(stringx.Remove(signInFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	signInModel interface {
		Insert(ctx context.Context, data *SignIn) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SignIn, error)
		Update(ctx context.Context, data *SignIn) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSignInModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SignIn struct {
		Id       int64  `db:"id"`
		Email    string `db:"email"`    // 邮箱
		Password string `db:"password"` // 密码
	}
)

func newSignInModel(conn sqlx.SqlConn) *defaultSignInModel {
	return &defaultSignInModel{
		conn:  conn,
		table: "`signIn`",
	}
}

func (m *defaultSignInModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSignInModel) FindOne(ctx context.Context, id int64) (*SignIn, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", signInRows, m.table)
	var resp SignIn
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSignInModel) Insert(ctx context.Context, data *SignIn) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, signInRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Email, data.Password)
	return ret, err
}

func (m *defaultSignInModel) Update(ctx context.Context, data *SignIn) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, signInRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Email, data.Password, data.Id)
	return err
}

func (m *defaultSignInModel) tableName() string {
	return m.table
}
