// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"SEproject/biz/application/service"
	"SEproject/biz/infrastructure/config"
	"SEproject/biz/infrastructure/mapper"
	"SEproject/biz/infrastructure/redis"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	signInModel := mapper.NewSignInModel(configConfig)
	redisRedis := redis.NewRedis(configConfig)
	signInService := &service.SignInService{
		Config:     configConfig,
		UserMapper: signInModel,
		Redis:      redisRedis,
	}
	providerProvider := &Provider{
		Config:        configConfig,
		SignInService: signInService,
	}
	return providerProvider, nil
}
